CREATE OR REPLACE TABLE `pdme000840-id3am42qxoa-furyid.STG.LK_FADS_SELLERS_ELEGIBILIDAD_ACTUAL` AS

WITH REPUTACION AS
(
  SELECT
    SIT_SITE_ID,
    CUS_CUST_ID               AS SELLER_ID,
    RE3_CURRENT_LEVEL         AS REPUTACION_ACTUAL
  FROM `meli-bi-data.WHOWNER.BT_SELLER_REPUTATION`
),

FACTURACION AS
(
  SELECT
    SIT_SITE_ID,
    COALESCE(PRINCIPAL_SELLER_ID, ADVERTISER_ID, 0) AS SELLER_ID,
    MAX(BILLING_STRATEGY)                           AS BILLING_STRATEGY_ACTUAL
  FROM `meli-bi-data.WHOWNER.LK_ADS_ADVERTISERS`
  WHERE COALESCE(PRINCIPAL_SELLER_ID, ADVERTISER_ID, 0) <> 0
  GROUP BY SIT_SITE_ID, SELLER_ID
),

TABLA_MI_PAGINA_ACTUAL_SELLER AS
(
  SELECT
    SIT_SITE_ID,
    STO_OWNER_ID AS SELLER_ID,
    1            AS FLAG_MI_PAGINA_ACTIVA_ACTUAL
  FROM `meli-bi-data.WHOWNER.LK_STOREFRONTS_CUSTOMERS`
  WHERE
    CASE
      WHEN STO_STATUS  = 'active'
        AND STO_TYPE    IN ('seller', 'brand')
        AND STO_CHANNEL = 'marketplace'
        AND SIT_SITE_ID IN ('MLA','MLB','MLM','MLC','MCO','MLU','MPE')
        AND 'normal_store'        IN UNNEST(STO_TAGS)
        AND 'car_dealer'      NOT IN UNNEST(STO_TAGS)
        AND 'real_estate_agency' NOT IN UNNEST(STO_TAGS)
        AND (
          'forced' NOT IN UNNEST(STO_TAGS)
          OR (
            'forced' IN UNNEST(STO_TAGS)
            AND EXISTS (
              SELECT 1
              FROM UNNEST(STO_ATTRIBUTES) attr
              WHERE attr.STO_ATTRIBUTES_KEY   = 'brand_attributes.brand_registry_id'
                AND attr.STO_ATTRIBUTES_VALUE != 'null'
            )
          )
        )
      THEN 1 ELSE 0
    END = 1
  GROUP BY ALL
),

ELEGIBILIDAD AS
(
  SELECT
    S.SIT_SITE_ID,
    S.STO_OWNER_ID AS SELLER_ID,
    MAX(CASE WHEN ET.eshop_target_status IN ('TARGET', 'HIRED') THEN 1 ELSE 0 END) AS FLAG_ESHOP_ELIGIBLE
  FROM `meli-sbox.FOLLOWADS.ads-display-dsp-lite-middleend_eshop_target` ET
  JOIN `meli-bi-data.WHOWNER.LK_STOREFRONTS_CUSTOMERS` S
    ON ET.ESHOP_ID   = S.STO_ID
   AND S.STO_CHANNEL = 'marketplace'
   AND S.STO_TYPE    IN ('seller', 'brand')
  WHERE ET.deleted_at IS NULL
  GROUP BY ALL
  HAVING FLAG_ESHOP_ELIGIBLE = 1
),

UNION_TABLAS AS
(
  SELECT SIT_SITE_ID, SELLER_ID, REPUTACION_ACTUAL,     NULL AS BILLING_STRATEGY_ACTUAL, 0 AS FLAG_MI_PAGINA_ACTIVA_ACTUAL, 0 AS FLAG_ELEGIBLE_ACTUAL FROM REPUTACION
  UNION ALL
  SELECT SIT_SITE_ID, SELLER_ID, NULL AS REPUTACION_ACTUAL, BILLING_STRATEGY_ACTUAL,       0 AS FLAG_MI_PAGINA_ACTIVA_ACTUAL, 0 AS FLAG_ELEGIBLE_ACTUAL FROM FACTURACION
  UNION ALL
  SELECT SIT_SITE_ID, SELLER_ID, NULL AS REPUTACION_ACTUAL, NULL AS BILLING_STRATEGY_ACTUAL, FLAG_MI_PAGINA_ACTIVA_ACTUAL,       0 AS FLAG_ELEGIBLE_ACTUAL FROM TABLA_MI_PAGINA_ACTUAL_SELLER
  UNION ALL
  SELECT SIT_SITE_ID, SELLER_ID, NULL AS REPUTACION_ACTUAL, NULL AS BILLING_STRATEGY_ACTUAL, 0 AS FLAG_MI_PAGINA_ACTIVA_ACTUAL,   1 AS FLAG_ELEGIBLE_ACTUAL FROM ELEGIBILIDAD
)

SELECT
  SIT_SITE_ID,
  SELLER_ID,
  MAX(REPUTACION_ACTUAL)           AS REPUTACION_ACTUAL,
  MAX(BILLING_STRATEGY_ACTUAL)     AS BILLING_STRATEGY_ACTUAL,
  MAX(FLAG_MI_PAGINA_ACTIVA_ACTUAL) AS FLAG_MI_PAGINA_ACTIVA_ACTUAL,
  MAX(FLAG_ELEGIBLE_ACTUAL)        AS FLAG_ELEGIBLE_ACTUAL
FROM UNION_TABLAS
GROUP BY ALL;
