-- Reputacion y billing: misma fuente que FADS, distinto nombre de columna en PADS
UPDATE `pdme000840-id3am42qxoa-furyid.TBL.DM_FRAME_PADS_MONTHLY_SELLERS` AS X
SET
    X.MODE_REPUTATION  = Y.REPUTACION_ACTUAL,
    X.BILLING_STRATEGY = Y.BILLING_STRATEGY_ACTUAL
FROM `pdme000840-id3am42qxoa-furyid.STG.LK_FADS_SELLERS_ELEGIBILIDAD_ACTUAL` AS Y
WHERE X.SIT_SITE_ID = Y.SIT_SITE_ID
  AND X.SELLER_ID   = Y.SELLER_ID;

-- Elegibilidad: desde POTENTIAL_ADVERTISERS
UPDATE `pdme000840-id3am42qxoa-furyid.TBL.DM_FRAME_PADS_MONTHLY_SELLERS` AS X
SET X.POTENTIAL_ADV = Y.CAN_BE_ADV
FROM `pdme000840-id3am42qxoa-furyid.STG.POTENTIAL_ADVERTISERS` AS Y
WHERE X.SIT_SITE_ID = Y.SIT_SITE_ID
  AND X.SELLER_ID   = Y.SELLER_ID;

-- Segmento marketplace: foto actual de LK_SEGMENTO_SELLERS
UPDATE `pdme000840-id3am42qxoa-furyid.TBL.DM_FRAME_PADS_MONTHLY_SELLERS` AS X
SET X.SEGMENTO_ASESORIA_MARKETPLACE_ACTUAL = Y.MODELO_ASESORIA_PRINCIPAL
FROM `meli-bi-data.WHOWNER.LK_SEGMENTO_SELLERS` AS Y
WHERE X.SIT_SITE_ID = Y.SIT_SITE_ID
  AND X.SELLER_ID   = Y.CUS_CUST_ID_SEL;
