-- CAN_BE_ADV desde POTENTIAL_ADVERTISERS
UPDATE `pdme000840-id3am42qxoa-furyid.TBL.DM_FRAME_PADS_DAILY_CAMPAIGN` AS X
SET X.CAN_BE_ADV = Y.CAN_BE_ADV
FROM `pdme000840-id3am42qxoa-furyid.STG.POTENTIAL_ADVERTISERS` AS Y
WHERE X.SIT_SITE_ID = Y.SIT_SITE_ID
  AND X.SELLER_ID   = Y.SELLER_ID;

-- REPUTACION_ACTUAL y BILLING_STRATEGY_ACTUAL: misma fuente que FADS
UPDATE `pdme000840-id3am42qxoa-furyid.TBL.DM_FRAME_PADS_DAILY_CAMPAIGN` AS X
SET
    X.REPUTACION_ACTUAL        = Y.REPUTACION_ACTUAL,
    X.BILLING_STRATEGY_ACTUAL  = Y.BILLING_STRATEGY_ACTUAL
FROM `pdme000840-id3am42qxoa-furyid.STG.LK_FADS_SELLERS_ELEGIBILIDAD_ACTUAL` AS Y
WHERE X.SIT_SITE_ID = Y.SIT_SITE_ID
  AND X.SELLER_ID   = Y.SELLER_ID;
