UPDATE `pdme000840-id3am42qxoa-furyid.TBL.DM_FRAME_PADS_MONTHLY_ITEMS` AS X
SET X.CAN_BE_ADV = Y.CAN_BE_ADV
FROM `pdme000840-id3am42qxoa-furyid.STG.POTENTIAL_ADVERTISERS` AS Y
WHERE X.SIT_SITE_ID = Y.SIT_SITE_ID
  AND X.SELLER_ID   = Y.SELLER_ID;
